spring.application.name=academic-assistant
# Configuración de conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/AsistenteBD
spring.datasource.username=postgres
spring.datasource.password=060805
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuración de Inteligencia Artificial
gemini.api.key=${GEMINI_API_KEY:TU_API_KEY_AQUI}
